[[redirects]]
  from= "/*"
  to="./Lost.html"
  status=200
  [[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[build]
  command = "npm run build"
  publish = "dist"