[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "20.x"

[[plugins]]
  package = "@netlify/plugin-inline-source"

[[plugins]]
  package = "@netlify/plugin-minify"

[build.environment]
  NODE_ENV = "production"

[[plugins.inputs]]
  include = "**/*.html, **/*.css, **/*.js"
  minify_html = true
  minify_css = true
  minify_js = true